const ADD_TO_PUBLIC_CARD_TYPE = {
    PLAY: "PLAY",
    THROW: "THROW",
    CHAI: "CHAI",
}

const EMIT_TYPE = {
    "DISCONNECT": "disconnect",

    "REJOIN_ROOM": "REJOIN_ROOM",
    "REFRESH_ROOMS": "REFRESH_ROOMS",
    "JOIN_ROOM": "JOIN_ROOM",
    "SWITCH_TEAM_MEMBER": "SWITCH_TEAM_MEMBER",
    "REFRESH_ROOM_PLAYERS": "REFRESH_ROOM_PLAYERS",

    "INIT": "INIT",
    "REFRESH_STATUS": "REFRESH_STATUS",

    "ACTION": "ACTION",
    "RESPONSE": "RESPONSE",
    "END_PLAY": "END_PLAY",
    "THROW": "THROW",
    "CARD_BOARD_ACTION": "CARD_BOARD_ACTION",
    "WUGU_BOARD_ACTION": "WUGU_BOARD_ACTION",
    "HERO_SELECT_BOARD_ACTION": "HERO_SELECT_BOARD_ACTION",

    "NOTIFY_ADD_TO_PLAYER_CARD": "NOTIFY_ADD_TO_PLAYER_CARD",
    "NOTIFY_ADD_TO_PUBLIC_CARD": "NOTIFY_ADD_TO_PUBLIC_CARD",
    "NOTIFY_ADD_LINES": "NOTIFY_ADD_LINES",

    // DEBUG
    "GO_NEXT_STAGE": "GO_NEXT_STAGE",
}

export {
    ADD_TO_PUBLIC_CARD_TYPE,
    EMIT_TYPE
}
