const RESPONSE_TYPE_CONFIG = {
    TAO: "TAO",
    SHAN: "SHAN",
    SKILL: "SKILL",
    WUXIE: "WUXIE",
    WEAPON: "WEAPON",
    SCROLL: "SCROLL"
}

export type RESPONSE_TYPE_CONFIG_KEYS = keyof typeof RESPONSE_TYPE_CONFIG;
export type RESPONSE_TYPE_CONFIG_VALUES = typeof RESPONSE_TYPE_CONFIG[RESPONSE_TYPE_CONFIG_KEYS];

export {
    RESPONSE_TYPE_CONFIG,
}