const RESPONSE_TYPE_CONFIG = {
    TAO: "TAO",
    CARD: "CARD",
    SKILL: "SKILL",
    CARD_BOARD: "CARD_BOARD",
    FAN_JIAN_BOARD: "FAN_JIAN_BOARD",
    GUAN_XING_BOARD: "GUAN_XING_BOARD",
    WUXIE: "WUXIE",
    SCROLL: "SCROLL"
}

export type RESPONSE_TYPE_CONFIG_KEYS = keyof typeof RESPONSE_TYPE_CONFIG;
export type RESPONSE_TYPE_CONFIG_VALUES = typeof RESPONSE_TYPE_CONFIG[RESPONSE_TYPE_CONFIG_KEYS];

export {
    RESPONSE_TYPE_CONFIG,
}