const TOOL_TIP_CARD_MAX_LENGTH = 50
const TOOL_TIP_HERO_MAX_LENGTH_CN = 40
const TOOL_TIP_HERO_MAX_LENGTH_EN = 60

export {
    TOOL_TIP_CARD_MAX_LENGTH,
    TOOL_TIP_HERO_MAX_LENGTH_CN,
    TOOL_TIP_HERO_MAX_LENGTH_EN
}