const TOOL_TIP_CARD_MAX_LENGTH_CN = 40
const TOOL_TIP_CARD_MAX_LENGTH_EN = 60
const TOOL_TIP_HERO_MAX_LENGTH_CN = 40
const TOOL_TIP_HERO_MAX_LENGTH_EN = 60
const PANDING_EFFECT_LENGTH_CN = 15
const PANDING_EFFECT_LENGTH_EN = 20

export {
    TOOL_TIP_CARD_MAX_LENGTH_CN,
    TOOL_TIP_CARD_MAX_LENGTH_EN,

    TOOL_TIP_HERO_MAX_LENGTH_CN,
    TOOL_TIP_HERO_MAX_LENGTH_EN,

    PANDING_EFFECT_LENGTH_CN,
    PANDING_EFFECT_LENGTH_EN,
}