const TOOL_TIP_CARD_TYPE = {
    CARD: "CARD",
    PUBLIC_CARD: "PUBLIC_CARD",
    EQUIPMENT: "EQUIPMENT",

    SELECTING_HERO: "SELECTING_HERO",
    PLAYER: "PLAYER"
}

export {
    TOOL_TIP_CARD_TYPE,
}
