const TOOL_TIP_CARD_TYPE = {
    // card
    CONTROL_CARD: "CONTROL_CARD",
    PUBLIC_CARD: "PUBLIC_CARD",
    EQUIPMENT: "EQUIPMENT",
    PANDING_CARD: "PANDING_CARD",

    SELECTING_HERO: "SELECTING_HERO",
    PLAYER: "PLAYER"
}

export {
    TOOL_TIP_CARD_TYPE,
}
